name: Auto feature branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to trigger the build for"
        required: true
      sha:
        description: "The last commit SHA that triggered the upstream"
        required: true
      feature:
        description: "The feature branch name to create"
        required: true

jobs:
  branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      
      - id: branch
        run: |
          echo '::set-output exists=$( git ls-remote --heads git@github.com:domtronn/pong.git ${{ github.events.input.feature }} | wc -l )::0'
         
      - uses: actions/github-script@0.4.0
        if: ${{ steps.branch.outputs.exists }} == 0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ github.events.inputs.feature }}`,
              sha: context.sha
            })
      
