name: Auto feature branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to trigger the build for"
        required: true
      sha:
        description: "The last commit SHA that triggered the upstream"
        required: true
      feature:
        description: "The feature branch name to create"
        required: true

jobs:
  branch:
    runs-on: ubuntu-latest

    steps:
      # Checkout the project to get git context
      - uses: actions/checkout@v2

      # Use toolkit actions script to determine if the feature branch already exists
      - id: branch-exists
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            try {
              const res = await github.repos.getBranch({
                owner: context.repo.owner, repo: context.repo.repo, 
                branch: `${{ github.event.inputs.feature }}`
              })
              core.info(`${{ github.event.inputs.feature }} exists, skipping branch creation`)  
            } catch (e) {
              core.info(e.toString())
              core.info(`${{ github.event.inputs.feature }} does not exist`)
              github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/heads/${{ github.event.inputs.feature }}`,
                sha: context.sha
              })
              return false
            }
        
      # Checkout the feature branch post creation or existing
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/${{ github.event.inputs.feature }}
          
      # Commit a file to keep the feature branch alive, similar to a touch
      - run: |
          date > ping.txt
          echo "Triggered by ping branch: ${{ github.event.inputs.branch }}@${{ github.event.inputs.sha }}" >> ping.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ping.txt
          git commit -m "Updated depdendent timestamp file for feature branch"
          git push
