name: Auto feature branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to trigger the build for"
        required: true
      sha:
        description: "The last commit SHA that triggered the upstream"
        required: true
      feature:
        description: "The feature branch name to create"
        required: true

jobs:
  branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
         echo "We got a new EVCore branch to play with!!! '${{ github.event.inputs.branch }}''"
         
         
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{ github.events.inputs.feature }}'
      
