on: push

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: branch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            try {
              await github.repos.getBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: `other-branch`
              })
              
              return true
            } catch (e) {
              return false
            }
            
      - run: |
          echo Result -> ${{ steps.branch.outputs.result }}
