on: push

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.info("Starting")
            const res = await github.git.ref({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/main`
            })
              
            core.info(res)
                            
            const newres = await github.git.ref({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/ping/pong`,
            })

            core.info(newres)
