on: push

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.info("Starting")
            const res = await github.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: `main`
            })
              
            core.info(res)
                            
            const newres = await github.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/heads/ping/pong`,
            })

            core.info(newres)
