on: push

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.info("Starting")
            const res = await github.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: `other-branch`
            })
              
            core.info(JSON.stringify(res, null, 2))
                            
